"""added field

Revision ID: 840a7c8e117d
Revises: 8fded712ffef
Create Date: 2021-05-26 19:29:00.602701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840a7c8e117d'
down_revision = '8fded712ffef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='Статус заявки'), schema='meet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'status', schema='meet')
    # ### end Alembic commands ###
