version: "3.5"

services:
  pg:
    image: postgres:12
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/var/app
    command: uvicorn main:app
    depends_on:
      - pg
  watcher:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python scripts/resend_tg_msg.py
    depends_on:
      - app
